# Generated by Django 6.0.5 on 2026-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('facilities', 'Facilities'), ('administration', 'Administration'), ('extracurricular', 'Extracurricular'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
